### PR TITLE
avoid warnings in Dict and Tuple types

### PR DESCRIPTION
**Pull request by haarg**

### CODE REVIEW

**Comment by haarg** [comment]
Fixes #24

**Comment by karenetheridge** [comment]
As discussed on #moose, the warnings were: "Found = in conditional, should be == at (eval 1295) line 285."

**Comment by robrwo** [comment]
I've run into this bug in actual code, and would appreciate the fix being merged. See https://gist.github.com/robrwo/194b789a69d7fe6e048a

**Comment by zisten** [comment]
+1

**Comment by robrwo** [comment]
The following test can be used:

``perl
use strict;
use warnings;

use Test::More;
use Test::Warnings;

use Types::Standard -all;
my $value = { key => 'value' };
my $type = Dict[key => Str];

eval $type->coercion->inline_coercion('$value');

done_testing;
```

**Pull request merged**
