### PR TITLE
fixed bad caller file names and line numbers in error messages

### PR DESCRIPTION
**Pull request by agentzh**
This issue is because of the fact that `Error::TypeTiny` did not ignore Moo's `Method::Generate::Constructor` package in the caller chain, as reported in #26.

### CODE REVIEW

**Comment by agentzh** [comment]
@ilmari Nice catch! Just pushed a commit in the same branch. Thanks a lot!

**Comment by cazador481** [comment]
Is there an expected release with this fix?

**Comment by haarg** [comment]
This PR should not be merged.  Adding foreign classes to `%CarpInternal` is the wrong thing to do.  Using `@CARP_NOT` may be more appropriate.

**Comment by tobyink** [comment]
Agree with @haarg.

**Comment by tobyink** [comment]
PR #35 might provide what you wanted though. I've just accepted that.

**Pull request closed without merging**
