### PR TITLE
Smartmatch discontinued beginning perl-5.41.3

### PR DESCRIPTION
**Pull request by jkeenan**
This patch adapts Type-Tiny to changes in the Perl core distribution becoming effective with monthly dev release perl-5.41.3, anticipated for the coming week.  Please review and, if acceptable, issue a new CPAN release at your earliest opportunity, as that will be helpful for further automated testing of this distribution's many reverse dependencies.

Thank you very much.

### CODE REVIEW

**Comment by jkeenan** [comment]
> This patch adapts Type-Tiny to changes in the Perl core distribution becoming effective with monthly dev release perl-5.41.3, anticipated for the coming week. Please review and, if acceptable, issue a new CPAN release at your earliest opportunity, as that will be helpful for further automated testing of this distribution's many reverse dependencies.
> 
> Thank you very much.

@tobyink, can you please review the changes in this pull request?  Thanks.

**Review by tobyink — APPROVED** [review]

**Comment by jkeenan** [comment]
@tobyink, thanks.  Once we get a new CPAN release, we will start to see a lot of CPANtesters reports from Type-Tiny's reverse dependencies.

**Comment by jkeenan** [comment]
> @tobyink, thanks. Once we get a new CPAN release, we will start to see a lot of CPANtesters reports from Type-Tiny's reverse dependencies.

@tobyink, could you indicate when a new CPAN release of Type-Tiny might be issued?  Because so many CPAN distributions have found Type-Tiny useful, there are many that can't be tested/installed in dependency order (*e.g.,* by CPANtesters) until Type-Tiny gets working from CPAN once again.

Thank you very much.

**Comment by tobyink** [comment]
I'm hoping this weekend for a dev version, with a full release two weeks later.

**Pull request merged**
